### ISSUE TITLE
SOM9331 support, reset when jumping after updating address for flash remap

### ISSUE THREAD

**Issue by AdriaanSwan** [pepe2k/u-boot_mod#102]
Hi,

I am adding support for the SOM9331 (http://www.openembed.com/index.php/goods/7/detail.html), but I have it a snag.

In ar933x_pll_init.S after updating the return address for the flash remap and then jumping to the new address the CPU resets. 

Any hints/ideas?

Thanks,
Adriaan

**Comment by AdriaanSwan** [comment]
Please ignore, the issue was with the lzma utility used on my 64bit system. After updating to correctly use the included lzma it all works as expected.

**Comment by pepe2k** [comment]
Hello @AdriaanSwan,

Thanks for info, lzma related issue is on my todo list.

Cheers,
Piotr
