### ISSUE TITLE
LigoWave NFT 1Ni - AR9341, 64M RAM, 16M (8M) FLASH

### ISSUE THREAD

**Issue by ZigFisher** [pepe2k/u-boot_mod#110]
Hi !
I start porting OpenWRT to LigoWave NFT 1Ni device.
After completion of the work, I lay in his GitHub.

Original LigoWave u-boot have dual-boot mode:
dev: size erasesize name
mtd0: 00030000 00010000 "u-boot"
mtd1: 00010000 00010000 "u-boot-env"
mtd2: 00120000 00010000 "kernel1"
mtd3: 00660000 00010000 "rootfs1"
mtd4: 00120000 00010000 "kernel2"
mtd5: 00660000 00010000 "rootfs2"
mtd6: 00090000 00010000 "data"
mtd7: 00020000 00010000 "cfg"
mtd8: 00010000 00010000 "art"
mtd9: 00780000 00010000 "firmware1"
mtd10: 00780000 00010000 "firmware2"
mtd11: 01000000 00010000 "flash"

And I need normal single-boot bootloader for AR9341 with 64M RAM and 16M FLASH (second variant - 8M FLASH).

You can help me ?  TNX !

**Comment by pepe2k** [comment]
Hello @ZigFisher,

What exactly do you want to know?

Cheers,
Piotr

**Comment by ZigFisher** [comment]
I apologize for the delay in replying.
I want to have a bootloader (binary file) for AR9341 with 16M Flash (25q128) and 64M RAM.
I do not have enough knowledge to compile from the source code.
Is it possible to get such a binary file?
TNX !

**Comment by pepe2k** [comment]
Hello @ZigFisher,

I haven't tested my code on any real platform with AR9341/AR9342 + DDR2, but I know from one of the users that there is some bug in DDR initialization and the board just doesn't start.

Till I get some AR9341/2 + DDR2 router, test it and eventually solve the problem, I can't help you.

Cheers,
Piotr

**Comment by pepe2k** [comment]
Hello @ZigFisher,

DDR2 ssetup on AR9341/2 is now fixed (https://github.com/pepe2k/u-boot_mod/commit/6bcd876a2b13dc9c6db90e15f91754e6c3c2d6d9), I can confirm that it works.

Cheers,
Piotr

**Comment by ZigFisher** [comment]
Hi !

I test it in next week and send report. Many Thank's !

**Comment by ZigFisher** [comment]
Yes, now correct work !
Thank you !
