### ISSUE TITLE
GL.iNet 6416A not loading kernel because of commit 8e83180 (with fix)

### ISSUE THREAD

**Issue by LaXiS96** [pepe2k/u-boot_mod#114]
Hi pepe2k,
during my tests today I noticed that I uboot always failed at recognizing the firmware and uncompressing the kernel of the CC release, while at 0x9F020000 everything looked good.
The issue is that you forgot to define CONFIG_TPLINK_IMAGE_HEADER to 1 for the gl-inet config in the uboot Makefile (as of [this commit](https://github.com/pepe2k/u-boot_mod/commit/8e831801e2adb288c3f1a776872d003622d4a398)), since it looks like OpenWrt does use the TPLink header format for the GL.iNet.
After I put that in and recompiled, everything went smooth as expected.

Thank you

**Comment by pepe2k** [comment]
Thanks!
