### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by sudden6** [pepe2k/u-boot_mod#124]
Probably a stupid question, but I haven't found any information about how to get to the download page of your modified u-boot, can you point me to it or mention it in the README?

**Comment by pepe2k** [comment]
https://github.com/pepe2k/u-boot_mod#ready-snapshottest-images

Cheers,
Piotr

**Comment by sudden6** [comment]
I just realized this was worded badly, I meant the instructions how to get to the webinterface of your bootloader. ie do I have to press any special buttons, load at the right time, or something else?

**Comment by pepe2k** [comment]
If you have serial access, you can interrupt booting and issue "httpd" command which will start web server. Or, use "reset" button, as described here: https://github.com/pepe2k/u-boot_mod#other

Cheers,
Piotr

**Comment by sudden6** [comment]
Thank you very much, IMHO this could be moved https://github.com/pepe2k/u-boot_mod#how-to-use-it so it's easier to find :)
