### ISSUE TITLE
bootloader image size

### ISSUE THREAD

**Issue by sudden6** [pepe2k/u-boot_mod#125]
I have the original u-boot image for a TP-LINK WR841N v11 and would like to add it to your collection, but I'm unsure about the size of the image needed to upload. Because my image is 128K in size whereas all other WR841N images are only 64K in size.

I checked the file with a hex editor and above 64K it's only `0xFF` besides two values (MAC adresses?), should I make a PR with the whole 128K or only the first 64K.

**Comment by pepe2k** [comment]
Please, provide first 64 KB only.

Cheers,
Piotr
