### ISSUE TITLE
when i use uboo-wdr3500 profile for 9344, the clock go slow

### ISSUE THREAD

**Issue by hanqingwu** [pepe2k/u-boot_mod#128]
when i complie uboot-wdr3500 profile for 9344, the clock  go slow, but when i use original_uboot_images/tp-link-wdr3500-v1 for test ,it's ok . 
who can tell my why ?

**Comment by pepe2k** [comment]
I know about the problem and it should be fixed soon.

**Comment by hanqingwu** [comment]
thanks!  i will wait for you .
