### ISSUE TITLE
Problem recovery

### ISSUE THREAD

**Issue by Ansuel** [pepe2k/u-boot_mod#130]
Today i had a problem with my firmware and i had to reflash it but when i tried to press the reset buttom to start the web page to recover my bricked router, it doesn't turn on the webpage
I then connected it to serial port and i watched what happen when i press the reset buttom.
So when i press it the router gives me from serial ##recovery not recognized 
platform is wdr3600

**Comment by pepe2k** [comment]
This text doesn't come from my code...

Cheers,
Piotr
