### ISSUE TITLE
unable to boot stock firmare using this u-boot

### ISSUE THREAD

**Issue by ThaiCat** [pepe2k/u-boot_mod#132]
Tested with current version built from sources and version integrated in openwrt 14.07. (router model is wdr3600)

**Comment by pepe2k** [comment]
https://github.com/pepe2k/u-boot_mod#known-issues

Cheers

**Comment by pepe2k** [comment]
Fixed in 894d49cd62c8adeac929ad9f376d4f0be061d9a9 and 5d22cded84ade76edd880dd65803a35bc70ad3ac.
