### ISSUE TITLE
Mikrotik rb941 support

### ISSUE THREAD

**Issue by samm-git** [pepe2k/u-boot_mod#133]
Hi, 

I am interesting in https://wiki.openwrt.org/toh/mikrotik/rb941_2nd support. Do you know if there is a chance that uboot will work on that device? I think if there is a chance i am brave enough to try :)

**Comment by pepe2k** [comment]
Hello @samm-git,

Platform is supported, it might work, but I have no idea how Mikrotik bootloader loads their kernel and if there is any special setup needed to make it working with stock firmware.

Cheers,
Piotr
