### ISSUE TITLE
Bootloader version detection.

### ISSUE THREAD

**Issue by thornley-touchstar** [pepe2k/u-boot_mod#137]
I'm just looking for suggestions regarding embedding a version string in the firmware build (in the non-compressed area) such that target operating system can detect the version of the boot loader currently running. 

If something already exists, that great, but if not, any ideas on how this should be implemented (structure/how/where/etc) would be great, I would be glad to add it.

**Comment by pepe2k** [comment]
Hi @thornley-touchstar,

I prefer this way: 280a01d3eef95af2efc3b875996acc01e7c26593

Cheers,
Piotr

**Comment by thornley-touchstar** [comment]
Agreed, it's much cleaner as part of the signature.
