### ISSUE TITLE
Please add support for QCA956x (TP-LINK TL-WR1043ND v4)

### ISSUE THREAD

**Issue by VittGam** [pepe2k/u-boot_mod#145]
Hello,

The new TP-LINK TL-WR1043ND v4 is based on QCA956x SoC (quite different from QCA955x of previous generation) and AR8337 switch chip (99.99% software compatible with AR8327, except for quirks and workarounds...).

It would be great to support it here.

The original u-boot uses TP-LINK "safeloader" new image format, but I personally don't think support for it would be needed here. I would be more than happy with a mktplinkfw (standard) compatible bootloader!

If I can somehow help, please tell me and I will try... :)

Cheers,
Vittorio

**Comment by ptpt52** [comment]
need this support too!
tp-link wdr6500 v7 is QCA956x soc

**Comment by vinibali** [comment]
AC1750 v4 is based on QCA9563 too.
@pepe2k, are you planning to do anything with the router you got previously?
_Thanks to M-K O'Connell for donating a router with QCA9563_

**Comment by pepe2k** [comment]
Sorry but this project is no longer maintained.
