### ISSUE TITLE
Would you please add support for AR7242 series

### ISSUE THREAD

**Issue by cgrrty** [pepe2k/u-boot_mod#147]
Hi Piotr
Would you please add support for AR7242 series, such as D-Link DIR-632 or  TP-Link TL-WR2543ND
For details
D-Link DIR-632  https://wiki.openwrt.org/toh/d-link/dir-632
TP-Link TL-WR2543ND https://wiki.openwrt.org/toh/tp-link/tl-wr2543nd
 
cheers
cgrrty

**Comment by pepe2k** [comment]
Hello @cgrrty,

This project doesn't and won't support EOL products, sorry.

Cheers
