### ISSUE TITLE
u-boot-upgrade script: unlock mtd / compare with backup after failure

### ISSUE THREAD

**Issue by kellogsgit** [pepe2k/u-boot_mod#155]
First, congratulations for this module. I have been looking for such a solution and it really rocks.

However, I was not able to use u-boot-upgrade from LEDE on WDR3600v1.
Probably the mtd is read-only and cannot be unlocked.

However, if possible:
1) the u-boot-upgrade script should test whether mtd is locked or not (or unlock it).
2) if upgrade fails, it should download the mtd immediately and check md5 and compare with backup. If md5 is same as backup, the mtd was not modified.

Kind regards,

**Comment by pepe2k** [comment]
Hi @kellogsgit,

> However, I was not able to use u-boot-upgrade from LEDE on WDR3600v1.
> Probably the mtd is read-only and cannot be unlocked.

This is a general rule in OpenWrt/LEDE. U-Boot partition is by default set as `read-only`. That's the reason for dedicated images (with unlocked U-Boot partition) in last release.

> However, if possible:
> 
>1. the u-boot-upgrade script should test whether mtd is locked or not (or unlock it).
>2. if upgrade fails, it should download the mtd immediately and check md5 and compare with backup. If md5 is same as backup, the mtd was not modified.

Both ideas sounds reasonable for me.
Unlock should be also possible with `mtd-rw` package.

Will put this on my "todo" list.

Thanks,
Piotr
