### ISSUE TITLE
Nexx WT3020 support?

### ISSUE THREAD

**Issue by nertia** [pepe2k/u-boot_mod#158]
Hi, I would like to enable failsafe for the Nexx 3020:
https://wiki.openwrt.org/toh/nexx/wt3020#dokuwiki__top

On the openWRT wiki there is a section on how to install the breed bootloader onto this device, but in this forum post:
https://forum.openwrt.org/viewtopic.php?id=55180
you say that this bootloader is based on your work.

 As it runs the  MediaTek MT7620n can you compile a binary for the WT3020?
 I do not want to run a closed source, GPL violating bootloader, but do not know the specific modifications required to compile it for this router.

**Comment by pepe2k** [comment]
MediaTek chipset are not supported in my code, sorry.

Cheers,
Piotr
