### ISSUE TITLE
Please update readme!

### ISSUE THREAD

**Issue by Sudokamikaze** [pepe2k/u-boot_mod#163]
When i tried to re-build this mod because version on my router is outdated, i can't even build. Then i checked in makefile names of routers.

In your readme:
```
tplink_wr841(for example)
```

In makefile it defined like
```
tp-link_tl-wr841n_v8
```

If you don't wanna update, or you don't have a free time i can create pull request to update readme with all names of devices

**Comment by pepe2k** [comment]
Hi @Sudokamikaze,

I really don't think that listing all targets will make sense. It would just add another place needed to be updated when support for a new device is added. There is a clear enough instruction in the README: "To build image, run `make model` inside top dir[...]".

Also, if your shell supports completion in make, you should be able to list all targets with `make \t\t`.

Cheers,
Piotr
