### ISSUE TITLE
Please add support for AR9342 (TP-Link TL-WR1041N)

### ISSUE THREAD

**Issue by cgrrty** [pepe2k/u-boot_mod#168]
Hi ：
Please add support for AR9342 (TP-Link TL-WR1041N)
System-On-Chip: | Atheros AR9342
Switch: | Atheros AR8327
https://wiki.openwrt.org/toh/tp-link/tl-wr1041n

Thanks!

**Comment by pepe2k** [comment]
Hello @cgrrty,

Platform is supported but I don't have access to that particular device, so it's up to you to make the code working on your device and then eventually send a pull request.

Cheers,
Piotr
