### ISSUE TITLE
Add support for TP-LINK RE450

### ISSUE THREAD

**Issue by mrkiko** [pepe2k/u-boot_mod#169]
This device seems not so easy to unbrick should a problem arise.
Thanks for the great incredible work.

**Comment by pepe2k** [comment]
Hello @mrkiko,

Please, see my answer for a similar question here: https://github.com/pepe2k/u-boot_mod/issues/168#issuecomment-319584899

Cheers,
Piotr

**Comment by mrkiko** [comment]
Thank you very much for your reply, really.
Yeah, reasonable.
Enrico
