### ISSUE TITLE
TP-Link MR3420 v3 EU

### ISSUE THREAD

**Issue by sumarouno** [pepe2k/u-boot_mod#178]
I have question for your great work. is it support for tp-link mr3420 v3 EU?
I've read the readme file, and MR3420 is there.

Thanks

**Comment by pepe2k** [comment]
Hi!

I don't have this device but someone else added support for it in #157 and I merged it, so it should be supported. I think you can ask author of the pull request if you have more questions.

Cheers!
Piotr
