### ISSUE TITLE
[question] tl-wdr3600 how to connect the serial TTL

### ISSUE THREAD

**Issue by emgiezet** [pepe2k/u-boot_mod#18]
Hello!

I just bricked my wdr3600 and looking for any spec how to connect usb ttl adapter to it

http://allegro.pl/show_item.php?item=3936803381

Any help will be cool!
Thx
Max

**Comment by louis966** [comment]
Hello. I have just bricked my wdr3600. I have ordered an USB serial device to fix it. Could you please explain me how you did it with yours? Thanks.

**Comment by pepe2k** [comment]
http://wiki.openwrt.org/toh/tp-link/tl-wdr4300#serial_console
