### ISSUE TITLE
 Web failsafe httpd question

### ISSUE THREAD

**Issue by zhangsd20** [pepe2k/u-boot_mod#182]
Hi pepe2k 
    HTTP server is starting at IP: 192.168.1.1 
    HTTP server is ready!
but my pc can't open the web and the ping failed ! why? 
Thanks !

**Comment by pepe2k** [comment]
Hi @zhangsd20

Is your PC configured with a static IP 192.168.1.x/24 (different than 192.168.1.1)?

Cheers,
Piotr

**Comment by zhangsd20** [comment]
Good morning：
            My pc IP 192.168.1.10 ，but  the problem is not there，I have found the problem and solved it。
Thank you very mach！

    













在2017年12月08 17时49分，"Piotr Dymacz"<notifications@github.com>写道：

Hi @zhangsd20
Is your PC configured with a static IP 192.168.1.x/24 (different than 192.168.1.1)?
Cheers,
Piotr

**Comment by mh4nx7net** [comment]
**no page found -- help**

![Screenshot from 2021-02-23 01-06-56](https://user-images.githubusercontent.com/33443311/108750317-73d59c80-7573-11eb-8059-7a29954b67ca.png)

```
    RAM: 32 MB DDR1 16-bit CL3-3-3-8
  FLASH: 4 MB Winbond W25Q32
    MAC: 00:03:7F:09:0B:AD
 CLOCKS: CPU/RAM/AHB/SPI/REF
         550/400/200/ 25/ 25 MHz

Keep button pressed for at least:
- 3s for web based recovery
- 5s for U-Boot console
- 7s for network console

. . . . 0x4 seconds

HTTP server is starting for firmware update...

Ethernet mode (duplex/speed): 1/100 Mbps
HTTP server is starting at IP: 192.168.1.1
HTTP server is ready!

Request for: /cgi-bin/luci/
## Error: file not found!
Request for: /cgi-bin/luci/style.css
## Error: file not found!
Request for: /favicon.ico
## Error: file not found!
Request for: /cgi-bin/luci/
## Error: file not found!
Request for: /cgi-bin/luci/style.css
## Error: file not found!
Request for: /favicon.ico
## Error: file not found!
Request for: /cgi-bin/luci/
## Error: file not found!
Request for: /cgi-bin/luci/style.css
## Error: file not found!
Request for: /favicon.ico
## Error: file not found!
```

i cant found any index.html by this repo :( where i can found them ?

**Comment by mpratt14** [comment]
http://192.168.1.1/index.html

**Comment by pepe2k** [comment]
Sorry but this project is no longer maintained.
