### ISSUE TITLE
Please add support for TP-LINK ARCHER C58 v1 & WR840N v2

### ISSUE THREAD

**Issue by AndyX-Net** [pepe2k/u-boot_mod#186]
Hi,@pepe2k

I have two TP-LINK router not on the support list, and i found some GPL documents(package of source code) from TP-LINK offical website, but i am not a programmer.

If you are free, Would you PLZ consider updating above routers to support list ?

TP-LINK ARCHER C58 v1
CPU: Qualcomm Atheros QCA9561
Flash: 8M (W25Q)
RAM: 64M
WLAN: Qualcomm Atheros QCA9561 & Qualcomm Atheros QCA9886
Offical GPL: http://static.tp-link.com/resources/gpl/Archer_C58_v1_GPL.tar.bz2

TP-LINK WR840N V2
CPU: Qualcomm Atheros QCA9533
Flash: 4M (W25Q)
RAM: 32M
WLAN/Switch: Qualcomm Atheros QCA9533
Offical GPL: http://static.tp-link.com/resources/gpl/TL-WR840v2_GPL.rar

Sorry my bad English.

Look forward to your reply！

**Comment by pepe2k** [comment]
Sorry but this project is no longer maintained.
