### ISSUE TITLE
Wallys DR344 UBOOT

### ISSUE THREAD

**Issue by oldcat618** [pepe2k/u-boot_mod#188]
Can you increase the Wallys DR344?

**Comment by pepe2k** [comment]
> Can you increase the Wallys DR344?

Increase what? This device isn't supported.

**Comment by oldcat618** [comment]
Add ar9344+ar8035 Uboot

**Comment by pepe2k** [comment]
Please, see my answer for a similar question here: https://github.com/pepe2k/u-boot_mod/issues/168#issuecomment-319584899

Cheers,
Piotr
