### ISSUE TITLE
question: Do you plan to release openwrt version with latest version of uboot?

### ISSUE THREAD

**Issue by kofec** [pepe2k/u-boot_mod#217]
Hi,
If you don't mind I have a few questions:
1. Do you plan to release openwrt version with latest version of uboot?
2. Is there any added value to flash latest version of uboot if I have version "2014-11-19" (and working fine) ?
    I have wdr3500, wdr3600, wdr4300
Thanks in advance

**Comment by CodeFetch** [comment]
@kofec What do you mean with releasing OpenWrt with latest version of U-Boot? OpenWrt will never release firmware that does bootloader modifications as flashing OpenWrt needs to be revertible to stock firmware without any traces being left. If you mean whether he'll release a "flash dump" including the modified bootloader and OpenWrt, this will likely not happen as there is still the ART partition that needs to be included and the partition layout differs between models. That's too much work. Just dump your ART-partition, flash the bootloader and use the webinterface to recover your ART partition and flash OpenWrt. If you want to automatize it, write some scripts to do that for you.

The added value is that you have a webinterface, network console etc. If you don't need it, there is no added value as U-Boot just boots your router and if it does, it works.

**Comment by kofec** [comment]
thanks for answer. I was thinking about:
https://github.com/pepe2k/u-boot_mod/releases/tag/2014-11-19
I'm testing ath79 vs ar71xx on my wdr3600. But till now I don't see any issue with uboot from the release "2014-11-19" but there are some changes after this release but it looks like there are not critical

**Comment by CodeFetch** [comment]
Please test if the changes also occur with the newest version and with the stock U-Boot. If they do it is an upstream issue of OpenWrt. This should not happen. This is the upgrade script you need:
https://github.com/pepe2k/u-boot_mod/blob/master/target_util/u-boot-upgrade

It should be compatible with the newest OpenWrt version.

**Comment by kofec** [comment]
Thanks for the answer.
The procedure is:
Compile image with module kmod-mtd-rw or it will be instlled if you use standard image.
Download or create on target/router script:
https://github.com/pepe2k/u-boot_mod/blob/master/target_util/u-boot-upgrade
create directory /etc/u-boot_mod/ and put there your uboot (for your router)
and just execute the above script:
```
root@OpenWrtWR842Nv3:~# ./u-boot-upgrade.sh

=======================================================
DISCLAIMER: you are using this script at your own risk!

The author of U-Boot modification and this script takes
no responsibility for any of the results of using them.

     Updating U-Boot is a very dangerous operation
   and may damage your device! You have been warned!
=======================================================

-----> Do you want to continue (type 'yes' or 'no')? yes

[ ok ] Found U-Boot image file: 'u-boot_mod__tp-link_tl-wr842n_v3__20180223__git_master-7a540a78.bin'

-----> Do you want to use this file (type 'yes' or 'no')? yes

[ ok ] MD5 checksum of new U-Boot image file is correct
[ ok ] Backup of /dev/mtd0 successfully created

-----> Do you want to store backup (recommended) in '/etc/u-boot_mod/backup/' (type 'yes' or 'no')? yes

[ ok ] Backup of '/dev/mtd0' successfully copied to '/etc/u-boot_mod/backup/'
[warn] Partition '/dev/mtd0' is not writable
[info] Unlocking '/dev/mtd0' partition...
[ ok ] Partition '/dev/mtd0' successfully unlocked
[ ok ] New U-Boot image successfully combined with backup file
[info] New U-Boot image is ready to be written into FLASH

-----> Do you want to continue (type 'yes' or 'no')? yes

[ ok ] New U-Boot image successfully written into FLASH
[ ok ] '/dev/mtd0' and new U-Boot image are equal
[info] Done! You can now reboot your device!
```
