### ISSUE TITLE
LAN's MAC addresses leaking to the WAN interface

### ISSUE THREAD

**Issue by ec-** [pepe2k/u-boot_mod#219]
On some models like TL-WDR4300 all 5 ports are configured to work as primitve switch before main firmware startup. So if you have both LAN and WAN interfaces configured to obtain IP addresses via DHCP - on very early stage LAN client may get direct WAN IP - which is VERY unsecure.

This is an explanaion why *at least* WAN port should be disabled https://github.com/pepe2k/u-boot_mod/blob/master/u-boot/board/ar7240/common/athrs17_phy.c#L136-L138

**Comment by pepe2k** [comment]
Sorry but this project is no longer maintained.
