### ISSUE TITLE
How to change RAM size allocation?

### ISSUE THREAD

**Issue by noeldum** [pepe2k/u-boot_mod#222]
I have an AR9371 module with 512Mb DDR2. This is a SKW71.
I flashed u-boot in the flash chip using the one build for the wr703n.
Initial welcome message from u-boot states that I have just 64Mb RAM.
How can I get u-boot to acknowledge the 512Mb?

**Comment by pepe2k** [comment]
512 Mb (megabits) == 64 MB (megabytes).

Cheers,
Piotr

**Comment by noeldum** [comment]
well done. That was easy. :/
