### ISSUE TITLE
Does the current support mt7688?

### ISSUE THREAD

**Issue by qq545305338** [pepe2k/u-boot_mod#226]

**Comment by CodeFetch** [comment]
No, only ath79 chipsets. I'm working on mt7688, but it will take some time.

**Comment by pepe2k** [comment]
@qq545305338 

MT76x8 series has support in mainline U-Boot, see:
https://github.com/u-boot/u-boot/commit/4c835a607bd5adf88a726c0f636b00dd31e50237

Cheers,
Piotr
