### ISSUE TITLE
uboot mod for Huawei B5328

### ISSUE THREAD

**Issue by coolirc** [pepe2k/u-boot_mod#231]
Hello i need some help concerning a 4G Lte device which uses uboot i have several devices that are stuck on some sort of a debug mode which telnet is enabled in this mode and i can see all the file system , partitions etc ... unfortunately when the device is working under normal mode the telnet is disabled and i can't stop the uboot from booting the kernel i think the manufacturer has disabled it ... i have only access to console port which are rx tx and gnd. 
here are informations about the device : 

the uboot log startup 
https://pastebin.com/8aeMcbvs
`

> dev:    size   erasesize  name
> mtd0: 00080000 00020000 "u-boot"
> mtd1: 00080000 00020000 "env"
> mtd2: 00100000 00020000 "rev0"
> mtd3: 00100000 00020000 "ltenv"
> mtd4: 00100000 00020000 "wmnv"
> mtd5: 00100000 00020000 "cmnnv"
> mtd6: 00100000 00020000 "cmnnv2"
> mtd7: 00400000 00020000 "rev1"
> mtd8: 00400000 00020000 "linux"
> mtd9: 00400000 00020000 "linux2"
> mtd10: 01e00000 00020000 "rootfs"
> mtd11: 01e00000 00020000 "rootfs2"
> mtd12: 00500000 00020000 "tk"
> mtd13: 00500000 00020000 "tk2"
> mtd14: 00080000 00020000 "customize"
> mtd15: 00280000 00020000 "log"
> mtd16: 02000000 00020000 "update"

`

`# uname -a
Linux B5328 3.10.0-uc0 #1 Wed Aug 24 09:38:10 CST 2016 armv7b GNU/Linux
# atc ati
sh: atc: command not found
# at
sh: at: command not found
# ls
bin      dev      etc      home     lib      linuxrc  mnt      proc     root     sbin     sys      tmp      usr      var
# mount
rootfs on / type rootfs (rw)
ubi0:rootfs on / type ubifs (ro,relatime)
proc on /proc type proc (rw,relatime)
ram on /var type ramfs (rw,relatime)
sys on /sys type sysfs (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,mode=666)
/dev/mtdblock15 on /var/log type jffs2 (rw,relatime)
#

# cat /proc/mounts
rootfs / rootfs rw 0 0
ubi0:rootfs / ubifs ro,relatime 0 0
proc /proc proc rw,relatime 0 0
ram /var ramfs rw,relatime 0 0
sys /sys sysfs rw,relatime 0 0
devpts /dev/pts devpts rw,relatime,mode=666 0 0
/dev/mtdblock15 /var/log jffs2 rw,relatime 0 0

# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 4 (v7b)
BogoMIPS        : 1652.73
Features        : swp half fastmult vfp edsp neon vfpv3 tls vfpv4 idiva
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 4

Hardware        : GCT GDM7243
Revision        : 0000
Serial          : 0000000000000000

`bootdelay=0
bootargs (default)
## Booting kernel from Legacy Image at d05fffc0 ...
   Image Name:   Linux-3.10.0-uc0
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    2317840 Bytes = 2.2 MiB
   Load Address: d0600000
   Entry Point:  d0600000
   Verifying Checksum ... Bad Data CRC
ERROR: can't get kernel image!
GDM7243>
GDM7243>
GDM7243> ls
Scanning JFFS2 FS:  done.
GDM7243> help

GDM7243> help
?       - alias for 'help'
askenv  - get environment variables from stdin
base    - print or set address offset
bootm   - boot application image from memory
bootp   - boot image via network using BOOTP/TFTP protocol
chpart  - change active partition
cmp     - memory compare
cp      - memory copy
crc32   - checksum calculation
ddri    - Print DDR information
dramt   - do DRAM Test
dramt2  - do DRAM Test2
fsinfo  - print information about filesystems
fsload  - load binary file from a filesystem image
go      - start application at address 'addr'
grfi    - Print GRF information
help    - print command description/usage
image   - GDM7243 image control (write, write_part, read, toggle, select)
loadb   - load binary file over serial line (kermit mode)
loady   - load binary file over serial line (ymodem mode)
loop    - infinite loop on address range
ls      - list files in a directory (default /)
md      - memory display
mm      - memory modify (auto-incrementing address)
mtdparts- define flash/nand partitions
mtest   - simple RAM read/write test
mw      - memory write (fill)
mwx     - memory write (incremental fill)
nand    - NAND sub-system
nandtest- GDM7243 nand test command
nboot   - boot from NAND device
nm      - memory modify (constant address)
ping    - send ICMP ECHO_REQUEST to network host
printenv- print environment variables
rarpboot- boot image via network using RARP/TFTP protocol
reset   - Perform RESET of the CPU
rst     - print reset key status
run     - run commands in an environment variable
saveenv - save environment variables to persistent storage
setenv  - set environment variables
sleep   - delay execution for some time
suspend - CPU suspend
tftpboot- boot image via network using TFTP protocol
version - print monitor version

GDM7243> mtdparts
GDM7243> mtdparts

device nand0 <gdm7243>, # parts = 17
 #: name                size            offset          mask_flags
 0: u-boot              0x00080000      0x00000000      0
 1: env                 0x00080000      0x00080000      0
 2: rev0                0x00100000      0x00100000      0
 3: ltenv               0x00100000      0x00200000      0
 4: wmnv                0x00100000      0x00300000      0
 5: cmnnv               0x00100000      0x00400000      0
 6: cmnnv2              0x00100000      0x00500000      0
 7: rev1                0x00400000      0x00600000      0
 8: linux               0x00400000      0x00a00000      0
 9: linux2              0x00400000      0x00e00000      0
10: rootfs              0x01e00000      0x01200000      0
11: rootfs2             0x01e00000      0x03000000      0
12: tk                  0x00500000      0x04e00000      0
13: tk2                 0x00500000      0x05300000      0
14: customize           0x00080000      0x05800000      0
15: log                 0x00280000      0x05880000      0
16: update              0x02000000      0x05b00000      0

active partition: nand0,0 - (u-boot) 0x00080000 @ 0x00000000

defaults:
mtdids  : nand0=gdm7243
mtdparts: mtdparts=gdm7243:512k(u-boot),512k(env),1m(rev0),1m(ltenv),1m(wmnv),1m(cmnnv),1m(cmnnv2),4m(rev1),4m(linux),4m(linux2),30m(rootfs),30m(rootfs2),5m(tk),5m(tk2),512k(customize),2560k(log),32m(update)`

`
here is the nand dump i could perform from telnet . [dump](http://www.mediafire.com/file/5jjxjof59i57192/nand_dumpB5328.zip/file)

i need to patch the uboot or a way to flash or take the firmware using tftp and uboot method 

thanks for help

**Comment by coolirc** [comment]
i was able to make a connection using serial port with rx tx and gnd now i was able to printenv but i am unable to ping to pc using address 192.168.0.10 which i set manually . 
is it because the current env variable **ethact=mii0**
gatewayip=192.168.0.1
netmask=255.255.255.0
ipaddr=192.168.0.1
serverip=192.168.0.10
ethact=mii0
pesifwcheck=1

here is the output of the command printenv : 

`
GDM7243> printenv
baudrate=921600
fs_permission=ro
nand0=gdm7243
mtdparts=mtdparts=gdm7243:512k(u-boot),512k(env),1m(rev0),1m(ltenv),1m(wmnv),1m(cmnnv),1m(cmnnv2),4m(rev1),4m(linux),4m(linux2),30m(rootfs),30m(rootfs2),5m(tk),5m(tk2),512k(customize),2560k(log),32m(update)
kernel_exec_addr=0xd05fffc0
kernel_load_addr=0xd0600000
file_load_addr=0xd0008000
cleanenv=nand erase.part env
linuxdn=loady ${kernel_load_addr}
imagedn=loady ${file_load_addr}
linuxsave=image write ${kernel_load_addr} linux ${filesize}
linux0save=image write_part ${kernel_load_addr} linux ${filesize}
linux2save=image write_part ${kernel_load_addr} linux2 ${filesize}
rootfssave=image write ${file_load_addr} rootfs ${filesize}
rootfs0save=image write_part ${file_load_addr} rootfs ${filesize}
rootfs2save=image write_part ${file_load_addr} rootfs2 ${filesize}
tksave=image write ${file_load_addr} tk ${filesize}
tk0save=image write_part ${file_load_addr} tk ${filesize}
tk0save=image write_part ${file_load_addr} tk2 ${filesize}
linuxsave2=nand erase.part linux;nand write ${kernel_load_addr} linux ${filesize}
rootfssave2=nand erase.part rootfs;nand write.jffs2 ${file_load_addr} rootfs ${filesize}
paramsave=nand erase.part param;nand write ${file_load_addr} param ${filesize}
bootsave=nand erase.part u-boot;nand write ${file_load_addr} u-boot ${filesize}
bswoecc=nand erase.part u-boot;nand write.woecc ${file_load_addr} u-boot ${filesize}
setbootargs=set bootargs console=ttyS0,${baudrate} boot=nand mem=${mem} ubi.mtd=10,2048 root=ubi0:rootfs ${fs_permission} rootfstype=ubifs ${mtdparts}
bootcmd=image read ${kernel_exec_addr} linux;bootm ${kernel_exec_addr}
bootcmd2=run setbootargs;nand read ${kernel_exec_addr} linux;bootm ${kernel_exec_addr}
webupdatekernel=0
webupdaterootfs=0
setfactrst=0
webupdkernelcmd=nand erase.part linux;nand read ${kernel_load_addr} upuimg ${partsize};nand write ${kernel_load_addr} linux ${partsize}
webupdrootfscmd=nand erase.part rootfs;nand read ${file_load_addr} upram ${partsize};nand write ${file_load_addr} rootfs ${partsize}
webupdatecmd=run webupdkernelcmd;run webupdrootfscmd;run bootcmd
factrstcmd=nand erase.part linux;nand read ${kernel_load_addr} factrst0 ${partsize};nand write ${kernel_load_addr} linux ${partsize};nand erase.part rootfs;nand read ${file_load_addr} factrst1 ${partsize};nand write ${file_load_addr} rootfs ${partsize}
upuimgsave=nand erase.part upuimg;nand write ${kernel_load_addr} upuimg ${filesize}
upramsave=nand erase.part upram;nand write.jffs2 ${file_load_addr} upram ${filesize}
factrst0save=nand erase.part factrst0;nand write.jffs2 ${kernel_load_addr} factrst0 ${filesize}
factrst1save=nand erase.part factrst1;nand write.jffs2 ${file_load_addr} factrst1 ${filesize}
tftpuboot=tftp ${file_load_addr} u-boot.bin
tftplinux=tftp ${kernel_load_addr} uImage
tftpcramfs=tftp ${file_load_addr} ramdisk.cramfs
tftpjffs2=tftp ${file_load_addr} ramdisk.jffs2
tftpubifs=tftp ${file_load_addr} ramdisk.ubifs
tftptk=tftp ${file_load_addr} tk.gz
ethaddr=00:0a:3b:f0:01:30
gatewayip=192.168.0.1
netmask=255.255.255.0
ipaddr=192.168.0.1
serverip=192.168.0.10
ethact=mii0
pesifwcheck=1
mtdids=nand0=gdm7243
mem=80M
op_bootargs=auto
bootdelay=5
stdin=serial
stdout=serial
stderr=serial
partition=nand0,0
mtddevnum=0
mtddevname=u-boot
pesifwcheckerr=1
bootargs=console=/dev/null,921600 boot=nand mem=80M ubi.mtd=10,2048 root=ubi0:rootfs ro rootfstype=ubifs mtdparts=gdm7243:512k(u-boot),512k(env),1m(rev0),1m(ltenv),1m(wmnv),1m(cmnnv),1m(cmnnv2),4m(rev1),4m(linux),4m(linux2),30m(rootfs),30m(rootfs2),5m(tk),5m(tk2),512k(customize),2560k(log),32m(update) bl_ver=0.46e checksum=disable active=linux,rootfs,unknown grf=gdm7243q

Environment size: 3645/131068 bytes
GDM7243>

`

`bootargs (auto)
## Booting kernel from Legacy Image at d05fffc0 ...
   Image Name:   Linux-3.10.0-uc0
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    2317840 Bytes = 2.2 MiB
   Load Address: d0600000
   Entry Point:  d0600000
   Verifying Checksum ... Bad Data CRC
ERROR: can't get kernel image!
GDM7243>
`

`GDM7243> mtdparts

device nand0 <gdm7243>, # parts = 17
 #: name                size            offset          mask_flags
 0: u-boot              0x00080000      0x00000000      0
 1: env                 0x00080000      0x00080000      0
 2: rev0                0x00100000      0x00100000      0
 3: ltenv               0x00100000      0x00200000      0
 4: wmnv                0x00100000      0x00300000      0
 5: cmnnv               0x00100000      0x00400000      0
 6: cmnnv2              0x00100000      0x00500000      0
 7: rev1                0x00400000      0x00600000      0
 8: linux               0x00400000      0x00a00000      0
 9: linux2              0x00400000      0x00e00000      0
10: rootfs              0x01e00000      0x01200000      0
11: rootfs2             0x01e00000      0x03000000      0
12: tk                  0x00500000      0x04e00000      0
13: tk2                 0x00500000      0x05300000      0
14: customize           0x00080000      0x05800000      0
15: log                 0x00280000      0x05880000      0
16: update              0x02000000      0x05b00000      0

active partition: nand0,0 - (u-boot) 0x00080000 @ 0x00000000

defaults:
mtdids  : nand0=gdm7243
mtdparts: mtdparts=gdm7243:512k(u-boot),512k(env),1m(rev0),1m(ltenv),1m(wmnv),1m(cmnnv),1m(cmnnv2),4m(rev1),4m(linux),4m(linux2),30m(rootfs),30m(rootfs2),5m(tk),5m(tk2),512k(customize),2560k(log),32m(update)
`
i deleted from telnet the partition of the kernel so the device is not able to load the kernel but i have a nand dump of each partition already made before on a working one .
now my question is how can i perform a backup of that partition using uboot ? 

thanks for help 

uboot version is 2010 

`U-Boot 2010.09 (Sep 06 2016 - 10:08:39)GCT GDM7243

Build Info:
  date: 2016/09/06-10:08:44
  user: root@ubuntu-will
  svnr:
  src: /home/will/DEVELOPMENT/LTE_Router/B5328_FDD/SDK/work/uboot
  ver: 0.46e
`

**Comment by CodeFetch** [comment]
This is not a forum and we don't offer help for random Huawei devices. Do us a favor and close this issue...

**Comment by coolirc** [comment]
Thanks for your reply i'll close the ticket , i'd expected some help from your side but thanks ...

**Comment by CodeFetch** [comment]
@coolirc This is just not the correct place, because this project has nothing to do with Huawei U-Boot and opening an issue in a different software project is not the correct way to ask for help. We don't know anything about Huawei-U-Boots and especially I don't know what you want to achieve. If you want to get a dump of the partitions, try to read it out directly. If that doesn't work, write a script that abuses the md command.

**Comment by pepe2k** [comment]
@CodeFetch 

> This is not a forum and we don't offer help for random Huawei devices. Do us a favor and close this issue...

"We"? Why are you speaking on my behalf? This is not your repository and not your project, so next time please be nice for others and speak only on your behalf.

Cheers,
Piotr

**Comment by CodeFetch** [comment]
Understood, but "we" was meant as people having to do with ath79 U-Boot. If you ask about motor issues with your yacht in a sports sailboat forum, I guess sailors would refer to themselves as "we", too. And I think it's also not nice to bug people opening an issue/bug report asking for help for a unrelated thing like in a forum.

**Comment by coolirc** [comment]
well i'm not totally out of subject like you say , i was hoping to port uboot to that board since it's a new chip and since that repository was named **U-boot_Mod** so it's actually being in the subject .

**Comment by CodeFetch** [comment]
@coolirc Ah okay... This U-Boot-Mod is for special WLAN routers with Qualcomm/Atheros chipsets. Your Huawei has a Realtek chipset and as you were already told in OpenWrt forum, chances are bad for easily supporting this device without source-code or proper specifications. 

Write an email to Huawei and ask them where to find the source code and if they don't have it available e.g. on the accompanying CD or on the internet, tell them they need to release the source-code as it's a GPL violation otherwise. This also includes the U-Boot source code (while I doubt that you need a custom U-Boot at all).

Personally I think this device is not worth the effort for trying to write a custom U-Boot or even supporting it in OpenWrt, because it is overpriced. I recommend you to sell it on eBay before it's getting completely outdated and worthless. I have bought a Huawei 4G router 2 years ago for $150 which at that moment costed more than $400 on eBay. Now it sells for under $30.

**Comment by coolirc** [comment]
sources : https://github.com/torvalds/linux/tree/master/drivers/staging/gdm724x

**Comment by CodeFetch** [comment]
@coolirc That's only the source code for the SoC. Please ask in the OpenWrt forum for help.
