### ISSUE TITLE
bootloader stuck at reboot (Dragino)

### ISSUE THREAD

**Issue by Shorosky** [pepe2k/u-boot_mod#238]
Hello:
Bootloader gets stuck when reboot Dragino 14MS.
If I shut-off and on the power, it starts ok.
Git: last commit: 7a540a78
toolchain: toolchain-mips_24kc_gcc-7.3.0_musl

---

Edit:
toolchain-mips_24kc_gcc-5.3.0_musl-1.1.16
toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16
gives the error too.
setting up #define DEBUG and BOARD_DEBUG, I get the following:
![image](https://user-images.githubusercontent.com/36064994/77864443-d077ec80-7228-11ea-9410-75f3a3c3ebe2.png)
when it reboots ok
and 

![image](https://user-images.githubusercontent.com/36064994/77864449-dec60880-7228-11ea-8056-7cc1520ba7d1.png)

When it is stuck in a reboot.

---

edit 10-05-2020
I have found that in function /u-boot_mod/u-boot/lib_mips/board.c -> board_init_f(ulong bootflag)
bootflag have to enter with 0x04000000 value, but sometimes, this value is a random number.
I have "fixed" it forcing bootflag argument to be 0x04000000. And it reset without problem.
However, the correct way to fix it is find the point of the program where it calls the function with incorrect value. I'll still working on it.

---

edit 17-05-2020
u-boot/cpu/mips/start.S contains the assembler instruction:
`la, t9, board_init_f`
`j t9`
And usually it sends value 0x04000000 as input arg. But, sometimes sends another value.
The assembler should charge input arg.on $a0 register, but I have not found where $a0 loads any value.

**Comment by pepe2k** [comment]
Hi @Shorosky 

I'm sorry for such a late reply. Could you please try below patches?

https://pastebin.com/qYqWHCJt
https://pastebin.com/PBEGUb4Y

Cheers,
Piotr

**Comment by Shorosky** [comment]
Hello @pepe2k 
It works. I have rebooted for 700 times the router and it doesn't hungs up now.
Is it going to be added at next git update?
Thanks for your help.
Regards

**Comment by pepe2k** [comment]
Sorry but this project is no longer maintained.
