### ISSUE TITLE
support for ZBT WE826-Q

### ISSUE THREAD

**Issue by lePereT** [pepe2k/u-boot_mod#239]
Hi pepe2k

Just wondered if your u-boot would function for the zbt we826-q, which is a qca953x based device based on the QCA AP147 reference design. `cat /proc/mtd` is as follows. Is there any more information I can provide? How would I go about seeing if code for the existing zbt qca953x routers (ZBT-WE1526 and ZBT-WE2226) worked here?

```
dev:    size   erasesize  name
mtd0: 00040000 00010000 "u-boot"
mtd1: 00010000 00010000 "u-boot-env"
mtd2: 00e30000 00010000 "rootfs"
mtd3: 00c40000 00010000 "rootfs_data"
mtd4: 00170000 00010000 "kernel"
mtd5: 00010000 00010000 "art"
mtd6: 00fa0000 00010000 "firmware"
```

**Comment by pepe2k** [comment]
Hi,

Please, see my answer for a similar question here: https://github.com/pepe2k/u-boot_mod/issues/168#issuecomment-319584899

Cheers,
Piotr
