### ISSUE TITLE
can't compile u-boot

### ISSUE THREAD

**Issue by ng91** [pepe2k/u-boot_mod#240]
I modded Makefile, beggining looks like this 

> export HOSTOS
> export HOSTARCH
> export BUILD_TOPDIR = $(PWD)
> export STAGING_DIR  = $(BUILD_TOPDIR)/tmp
> export SOURCE_DIR   = $(BUILD_TOPDIR)/u-boot
> export BIN_DIR      = $(BUILD_TOPDIR)/bin
> export MAKECMD=make --silent ARCH=mips CROSS_COMPILE=mips-openwrt-linux-uclibc-
> export PATH:=$(BUILD_TOPDIR)/toolchain/bin/:$(PATH)

Also i extracted a toolchain(recommended) to it's directory.
I'm getting such error - when i run main

> bash: gainstrong_oolite_v1_dev: nie znaleziono polecenia
> Makefile:227: recipe for target 'gainstrong_oolite_v1_dev' failed
> make: *** [gainstrong_oolite_v1_dev] Error 127

And when i run make tp-link_tl-wr740n_v4

> bash: tp-link_tl-wr740n_v4: nie znaleziono polecenia
> Makefile:227: recipe for target 'tp-link_tl-wr740n_v4' failed
> make: *** [tp-link_tl-wr740n_v4] Error 127

**Comment by pepe2k** [comment]
Hi @ng91 

You definitely did something wrong as the recommended toolchain is the one with `musl` but you have `mips-openwrt-linux-uclibc-`... you should fix your Makefile and make sure it uses correct toolchain.

Cheers,
Piotr
