### ISSUE TITLE
MR3020 and 128kb u-boot image

### ISSUE THREAD

**Issue by nopbit** [pepe2k/u-boot_mod#241]
Hello,
I want to upgrade my mr3020 from 4mb flash to 16mb flash. I am using ch341a programmer for this. I manually created an empty binary file filled with 0xFF. I inserted uboot, MAC address, WPS pin and model number to mentioned addresses. As i see on below image, i need to write "clock configuration (20 bytes)" but i have no idea what it is. What must i write to those address?

Thanks

![map](https://user-images.githubusercontent.com/2934612/29492794-9356aa98-8587-11e7-8a2c-04162154cd2e.png)

**Comment by pepe2k** [comment]
Hi @nopbit 

That area is only a reservation for clock configuration used by `setclk` and `clearclk`, you can just leave it empty (filled with 0xff).

Cheers,
Piotr
