### ISSUE TITLE
if I hard-mod flash to 16MiB should I change this uboot?

### ISSUE THREAD

**Issue by youxiaojie** [pepe2k/u-boot_mod#245]
for tp link 4310 4300 if I hard-mod flash to 16MiB should I change this uboot? ie mtd parameter pass to kernel? is the web update function affected?

**Comment by mpratt14** [comment]
If you are working with Openwrt then the uboot parameters do not matter, Openwrt will ignore them.

**Comment by youxiaojie** [comment]
yes openwrt, is the web firmware recovery function (you added) affected?

**Comment by lePereT** [comment]
Sorry to jump in here, I'm planning on modding almost the same device to 32MB flash using this chip (https://www.digikey.co.uk/product-detail/en/macronix/MX25L25673GM2I-08G/1092-1239-ND/7914983). Will that work?

**Comment by CodeFetch** [comment]
This U-Boot supports flash modifications, but OpenWrt does not.

**Comment by pepe2k** [comment]
Sorry but this project is no longer maintained.
