### ISSUE TITLE
u-boot for ZyXEL NBG6716

### ISSUE THREAD

**Issue by springtales** [pepe2k/u-boot_mod#252]
hi , pepe2k
I need urgently u-boot for this device (ZyXEL NBG6716) , it is QCA9558 , I think you already support this soc (QCA955x) , pls help me to download it or even a sdk to build . thanks

**Comment by pepe2k** [comment]
Try this one, it's a dump from my device.

[NBG6716_mtd0_u-boot.zip](https://github.com/pepe2k/u-boot_mod/files/6426571/NBG6716_mtd0_u-boot.zip)

**Comment by springtales** [comment]
thank you very much
