### ISSUE TITLE
Does u-boot_mod can help me to revert to stock tp-link firmware?

### ISSUE THREAD

**Issue by skater-boy** [pepe2k/u-boot_mod#254]
Hi all,

I have a TL-WA850RE v2 (italy) and I changed the firmware from original tp-link to OpenWRT to give it a try. Unfortunately OpenWRT doesn't allow settings to be stored for my device (not enough flash available) and at each reboot the configuration is lost. This makes OpenWRT solution totally unusable, of course!
So I decided to revert back to stock firmware. Here OpenWRT shows its second big limitation: is not possible to load a stock .bin and flash it from LuCi web gui! Also tested stripping away the bootloader-part from an original tp-link fw but no, OpenWRT doesn't accept this .bin as valid and doesn't start the flash procedure.

Since embedded u-boot is working I attempted the TFTP way to go back to stock fw. Unfortunately my u-boot seems to have no support for it. The tftp server at 192.168.0.66 receives no request at all from wa850re. Tested by holding pressed reset button on wa850re at power on, reset+wps, wps button only. Many combinations tested, 3 seconds, 5 seconds, ... Also tested tftp server alone with a tftp linux client and worked well. Also sniffed traffic with wireshark and saw no requests toward the tftp server.

So I opened the wa850re's shell and connected a 3v3 serial port. Using the serial port I erased the flash firmware area and written to it the original tp-link .bin file with the bootloader-part stripped by me. But I get a ''Too big uncompressed streamLZMA ERROR 1' and the wa850re reboots itself over and over (bricked device in other words). 
Also tested with the stripped .bin from https://openwrt.org/toh/tp-link/tl-wa850re. Same error.
So, with the same procedure, I restored the OpenWRT fw so the procedure itself is ok, tftp server is ok, ethernet cable is ok.
Procedure followed:
setenv serverip 192.168.1.100
tftpboot 0x80060000 openwrt.bin
erase 0x9f020000 +0x380004
cp.b 0x80060000 0x9f020000 0x380004
bootm 0x9f020000

Where 192.168.1.100 is the ip of the tftp server and 0x380004 the size in hex of the OpenWRT .bin firmware

As different attempt I copied a stripped tp-link .bin firmware using scp to /tmp directory of wa850re then fired a `mtd -r write /tmp/stripped.bin firmware`
Didn't worked :( and yields to a bricked device (but u-boot still working)
Also tried with `sysupgrade -F /tmp/stripped.bin`
Didn't worked :( and yields to a bricked device (but u-boot still working)

Also tested different fw from tp-link like the one for hw v1 or even for similar models like wa830re_v2 or TL-WR841ND_v8. Also tried with -us instead of -eu firmware. Different error than ZLMA but still not working and bricked device.

I'm now ready to ERASE u-boot and reaplce it with the mod.
Does u-boot_mod can help me to revert to stock tp-link firmware?

Thanks

**Comment by pepe2k** [comment]
Sorry but this project is no longer maintained.
