### ISSUE TITLE
MDIO_Busy Error after board revise

### ISSUE THREAD

**Issue by Ritesh236** [pepe2k/u-boot_mod#255]
Hello Pepe2K, 

We are using AR9331 based OOLITE Module V1. 0 into one of our product and designed new board with some GPIOs addition based on older board. 

So, Now, We are facing some MDIO_BUSY error on bootloader for 10 to 13 seconds contieously but we are not using Ethernet Interface into our product. 

We are using WiFi interfave for network communications. 

Please find below log for reference purpose. 

***************************************
*     U-Boot 1.1.4-858dd301-dirty     *
*          Build: 2021-05-21          *
***************************************

  BOARD: GainStrong Oolite v1-Dev
    SOC: AR9330 rev. 1
    CPU: MIPS 24Kc
    RAM: 64 MB DDR2 16-bit CL3-4-4-10
  FLASH: 16 MB Winbond W25Q128
    MAC: 00:03:7F:09:0B:AD
 CLOCKS: CPU/RAM/AHB/SPI/REF
         400/400/200/ 25/ 25 MHz

## Error: MDIO_BUSY!
ag7240_mii_setup: MDC check failed
## Error: MDIO_BUSY!
Hit any key to stop booting:  1 0

So, Can you please help us like what can be the reason  for this type of issues? 

Let me know if need anything else from my end. 

Regards, 
Ritesh Prajapati

**Comment by Ritesh236** [comment]
Hello Team,

Any update regarding issue which I have reported?

Let me know if need anything else from my end

Regards,
Ritesh Prajapati

**Comment by Ritesh236** [comment]
@pepe2k ,

Do you any idea for the same like how it can be resolved?

Regards,
Ritesh Prajapati

**Comment by pepe2k** [comment]
Sorry but this project is no longer maintained.
