### ISSUE TITLE
Caraboot 2.10 introduces startup fix to Carambola2

### ISSUE THREAD

**Issue by codehero** [pepe2k/u-boot_mod#256]
Hi, I was wondering if the change in

https://github.com/8devices/Caraboot/commit/df4836defb74abb3924fc22061c26fc6e7fe30ea

already existed in the u-boot_mod codebase?

**Comment by codehero** [comment]
I did some tests on my own with 3 different versions u-boot

Setup:
 Custom board with Carambola2-I with another microprocessor toggling Carambola reset line
 A script would run on the carambola instructing this microprocessor to toggle the reset line.
 A bash loop running on a host PC would ssh into the Carambola and call this script.
 So I was able to repeatedly test the reset line behaviour and stop when u-boot would lock up

Results:
Caraboot V2.3 -> would eventually lock up in u-boot
Caraboot V2.10 -> survived 100 loops
u-boot_mod, git commit b29f18ad9d27ba020f4d7a38b4ecda1c5aaca3a9 -> would eventually lock up in u-boot

I will update my u-boot_mod and reset

**Comment by codehero** [comment]
Updated u-boot_mod to latest and confirmed that I was having reset line issues. I think this fix should be in u-boot_mod as well

**Comment by codehero** [comment]
@pepe2k I have looked at porting their changes over but I think there is some deep domain knowledge, as well as JTAG access to the Carambola needed to do this right.
Can you please DM me @codehero, I would like to discuss a bounty for this work

**Comment by pepe2k** [comment]
Sorry but this project is no longer maintained.
