### ISSUE TITLE
loadb 

### ISSUE THREAD

**Issue by netkomltd** [pepe2k/u-boot_mod#35]
Hi Piotr,
Do you have a plan to add command like "loadb" (http://www.denx.de/wiki/view/DULG/UBootCmdGroupDownload#Section_5.9.5.3.) in your job ? This will be very useful for modules based on AR9331 (such a gs-oolite).They don't have built-in LAN connectors like routers . It will be very easily flashed through a serial console via kermit mode.
Best Regards

**Comment by pepe2k** [comment]
loadb/loady commands are available, tested and working on AR933x: https://github.com/pepe2k/u-boot_mod/commit/a404a56e48c2796e4621b42cd461bf5e95ea5e09

AR934x support is currently broken, I will fix it later.
USB support will be available soon on both platforms.

Cheers

**Comment by cj1324** [comment]
:+1:

**Comment by hackruu** [comment]
amazing, thanks!
