### ISSUE TITLE
uncompressed u-boot and rw env when larger flash installed

### ISSUE THREAD

**Issue by N1ght5tar** [pepe2k/u-boot_mod#46]
Question: It is possible to enable u-boot be uncompressed and to store settings to flash when flash chip is replaced with larger one? If so, how I can safely do that?
For example I have TL-MR3020 with 16M flash.

Note I do not have quick access to reflashing equipment.

**Comment by pepe2k** [comment]
Hello @N1ght5tar,

Short answer: yes, it's possible. Take a look on support for devices with writable environment like Dragino 2 or Carambola 2.

Keep in mind that this change will probably require also different OpenWrt image (different mtd partitions).

Regards

**Comment by N1ght5tar** [comment]
I already tried it but it bricked device, so I still needed reflash through soldering. But for some reason RAM version did work. Don't know why, I am going to experiment when only I will equipped well :-)

Thanks!

**Comment by pepe2k** [comment]
> I already tried it but it bricked device, so I still needed reflash through soldering. But for some reason RAM version did work. Don't know why, I am going to experiment when only I will equipped well :-)

RAM version worked, because it doesn't include low level initialization. If you use for example code for Carambola 2 and your device have different memory type or XTAL (25 MHz instead of 40 MHz) the normal (FLASH version) image will not work on tour device! This code is not fully universal, you need to adapt it for your device.

Regards

**Comment by N1ght5tar** [comment]
If I will post a patch can you see through it if it contains mistakes in the configuration? In it I just make everything flash related like how it's done for Carambola 2 but other parts I tried to leave or adapt like it is for my TL-MR3020.
