### ISSUE TITLE
Porting to Mediatek MIPS v2?

### ISSUE THREAD

**Issue by marcnicholas** [pepe2k/u-boot_mod#53]
Hi,

I took a quick look through the code, but was wondering your thoughts on porting this to another MIPS CPU -- in particular the MT762x series, which are becoming quite popular.

They're generally setup little endian (looks like that's an easy config change, at least) with v2 instructions (looks like v1 is configured now).

Other than that, I guess there's the hard work of initing RAM, low-level Flash routines (SPI), serial console, Ethernet etc?

Unreasonable for a newbie to achieve?

Thanks!

-m

**Comment by pepe2k** [comment]
https://github.com/cleanwrt/u-boot_mt7620

**Comment by marcnicholas** [comment]
:+1:  :D
