### ISSUE TITLE
NAND

### ISSUE THREAD

**Issue by acrixl** [pepe2k/u-boot_mod#59]
what about nand flash support?

**Comment by pepe2k** [comment]
Hello @acrixl,

Do you have any specific device/SoC in mind?

Cheers,
Piotr

**Comment by acrixl** [comment]
yes, like this
http://routerboard.com/RB951G-2HnD

based on AR9344-DC3A
have on board SPI flash 64KB for boot
and 126MB nand flash for user

i have this device, but spi flash dead, so i made hardware modification and add 4Mb spi flash
i build u-boot_mod for wdr3600_43x0 and it up and work, but linux for nand ar9xxx not view nand

**Comment by pepe2k** [comment]
Hello @acrixl,

For now, I don't plan support for any Mikrotik device, but I have on my "todo" list support for NAND on QCA955x WiSoCs.

Cheers,
Piotr
