### ISSUE TITLE
Big images

### ISSUE THREAD

**Issue by clehner** [pepe2k/u-boot_mod#61]
Are the 123K images safe to use on TP-Link devices? The readme says it would be a 64 KiB image, but when I built for a TL-WR703N I get a 125952-byte image.

**Comment by pepe2k** [comment]
They are safe only if you make backup and combine with rest of the content from your FLASH, from first two 64 KB sectors. You can use also ready images from last release, they are tested and safe.

**Comment by clehner** [comment]
Thanks. Unfortunately I already bricked it trying to flash openwrt so I'll have to set this aside for now.

**Comment by huangwarrenus** [comment]
You can still use a Flash programmer to debrick your device.


     On Monday, May 4, 2015 5:14 AM, Charles Lehner <notifications@github.com> wrote:
   

 Thanks. Unfortunately I already bricked it trying to flash openwrt so I'll have to set this aside for now.—
