### ISSUE TITLE
The latest sources

### ISSUE THREAD

**Issue by efidrin** [pepe2k/u-boot_mod#62]
Dear pepe2k.

I install and build and trie new sources , where You use NEW_UART_DRIVER and the image size is 123K.
 BUT, I think that I found some mistake. For example here 
https://github.com/pepe2k/u-boot_mod/blob/master/u-boot/include/configs/ap121.h#L1091

PLL_IN_FLASH_DATA_BLOCK_OFFSET is 64K, but new image have 123K 
Also OFFSET_MAC_DATA_BLOCK and OFFSET_MAC_DATA_BLOCK_LENGTH will be another

**Comment by pepe2k** [comment]
Hello @efidrin,

Those definitions are OK.
Please, take a look at my description in this commit: https://github.com/pepe2k/u-boot_mod/commit/9ac93275915e7353b2a32a8492b473362eb5d198

Cheers
