### ISSUE TITLE
compiling makes wrong image size

### ISSUE THREAD

**Issue by drsn0w** [pepe2k/u-boot_mod#69]
I modified some environment variables and the generated image is of the wrong size. compiling for TL-WR703N

**Comment by drsn0w** [comment]
the image that's built is 125952 long, instead of the correct 65536

**Comment by drsn0w** [comment]
123k vs 64k

**Comment by pepe2k** [comment]
https://github.com/pepe2k/u-boot_mod/commit/9ac93275915e7353b2a32a8492b473362eb5d198

**Comment by drsn0w** [comment]
yep my bad
