### ISSUE TITLE
TPLink WR941nd uboot

### ISSUE THREAD

**Issue by trueeike** [pepe2k/u-boot_mod#71]
Is it hard to make your ubood mod usable for TPLink WR941nd v3 based on Atheros AR9132?

**Comment by pepe2k** [comment]
Hello @trueeike,

No, it shouldn't be so hard. You have almost everything - GPL sources from TP-Link, sources of my modification... all you need to do is to combine those two things. From my POV, I don't want to focus on routers which aren't available on the market anymore (EOL).

Cheers
