### ISSUE TITLE
does this board support n2tu51216dg ddr, my board could't startup with this ddr

### ISSUE THREAD

**Issue by githubaudience** [pepe2k/u-boot_mod#74]

**Comment by githubaudience** [comment]
i want to know how to port ddr about code for new ddr ic use this uboot

**Comment by pepe2k** [comment]
And you board is... wait, don't tell me! I need only... where is my magic ball?

**Comment by githubaudience** [comment]
what's mean magic ball?

**Comment by pepe2k** [comment]
It means that you forgot to write what kind of board you are using...
