### ISSUE TITLE
run some bare metal mips code built with mkimage

### ISSUE THREAD

**Issue by zrafa** [pepe2k/u-boot_mod#77]
Hello pepe2k, 
  we are teaching mips assembly in our faculty, and we are interested to use your uboot in our devices (mr3020).
Mainly, we want to have more options than original bootloader from tplink device.
In our case, we want to build some code with mkimage without lzma, load on RAM with your uboot, and then jump to the code to run it. Would be that possible?
Our main problem with original uboot from device/tplink is that it just have the bootm command. Also, the only option is lzma binary file, and then we have not had success to build some baremetal mips code, lzma, and run it on mr3020 with original uboot. We can build openwrt and all goes okey, but no stand alone bare metal code. We always get some error with lzma or similar :(
Then, we want to know if we can avoid that lzma criter thing in the building process if we use your uboot. I mean, just using mkimage without lzma, load on ram and run.
Would that work?

thanks in advance,
Rafa

**Comment by pepe2k** [comment]
Hello Rafa,

My modification includes "go" command (https://github.com/pepe2k/u-boot_mod/commit/d5cd8136ef3bce467cbee184cbade0a7cde9c5ec), which may be what you are looking for.

Regards,
Piotr
