### ISSUE TITLE
Make it possible to backup whole flash from uboot

### ISSUE THREAD

**Issue by ghost** [pepe2k/u-boot_mod#80]
Is there a way to send flash image from uboot directly, without booting into "minimal environment" with downloaded kernel or other ways requiring to boot from uboot?
Since you have an embedded HTTP server, can it be an option to download (backup) whole flash from it?

Otherwise the mod is neat, I like it. Kudos for work!

**Comment by pepe2k** [comment]
`tftpput` command was added in f191a95f50c29cbaf76606611eb1a7a9353c9bd1 and can be used to dump whole/part of the FLASH easily, without entering linux environment.

Author of this question deleted his/her account from GitHub, so I'm closing this issue.
