### ISSUE TITLE
Again about 40MHz XTAL

### ISSUE THREAD

**Issue by efidrin** [pepe2k/u-boot_mod#83]
I continue trays with AP121 and 40MHz quartz.

Used MR3220 , with default FLASH and RAM . 
GPIO0 on start have 1 (as datashhet tell as)
Resolder XTAL .

Make u-boot version with CONFIG_40MHZ_XTAL_SUPPORT option 
 
With new UART drivers (thanks to Pepe2k) , I can see console output (br=38400)
Router started, even loads Openwrt (15.05)

BUT
Noone profile from "setclk" didnt work (only default 400_400_200 )
Not worked ethernet (not in u-boot , not when Openwrt loaded) and wireless 

![u-boot](https://cloud.githubusercontent.com/assets/11218742/10597354/c3d3a9a6-76f6-11e5-817a-0ebfdcd8febd.png)

**Comment by pepe2k** [comment]
Hello,

Try new code.

Cheers,
Piotr
