### ISSUE TITLE
Is now support DDR2 RAM type?

### ISSUE THREAD

**Issue by dlinkqu** [pepe2k/u-boot_mod#91]
Hi pepe2k:
    My demo board was use DDR2 RAM, I want to install this u-boot, but when I download WR703 uboot to my board, it can not run anymore. I have to take SPI FLASH programming to restore it. I think RAM type is the problem. So this u-boot is now support DDR2?

**Comment by huangwarrenus** [comment]
I think that pepe2k's uboot supporting DDR2 RAM very well. 

    On Thursday, February 18, 2016 3:34 PM, dlinkqu <notifications@github.com> wrote:
 

 Hi pepe2k:
 My demo board was use DDR2 RAM, I want to install this u-boot, but when I download WR703 uboot to my board, it can not run anymore. I have to take SPI FLASH programming to restore it. I think RAM type is the problem. So this u-boot is now support DDR2?—

**Comment by dlinkqu** [comment]
Problem solved! I have modified "hornet_ddr_init.S" for DDR2, and chang Makefile lzma  parameter---"$(LZMA) e $(obj)u-boot.bin u-boot.bin.lzma". U-boot now work well.
