### ISSUE TITLE
mips-openwrt-linux-musl-gcc.bin: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by stopspazzing** [pepe2k/u-boot_mod#94]
After changing to ```export MAKECMD=make --silent ARCH=mips CROSS_COMPILE=mips-openwrt-linux-```

>spazz@spazz-VirtualBox:~/Downloads/u-boot_mod$ make tplink_wdr3600_43x0
/home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-gcc: line 82: /home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-musl-gcc.bin: cannot execute binary file: Exec format error
/home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-gcc: line 82: /home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-musl-gcc.bin: Success
Makefile:154: warning: overriding recipe for target '.PHONY'
Makefile:152: warning: ignoring old recipe for target '.PHONY'
Makefile:240: warning: overriding recipe for target 'board/ar7240/db12x/libdb12x.a'
Makefile:208: warning: ignoring old recipe for target 'board/ar7240/db12x/libdb12x.a'
Makefile:240: warning: overriding recipe for target 'cpu/mips/libmips.a'
Makefile:208: warning: ignoring old recipe for target 'cpu/mips/libmips.a'
Makefile:240: warning: overriding recipe for target 'cpu/mips/ar7240/libar7240.a'
Makefile:208: warning: ignoring old recipe for target 'cpu/mips/ar7240/libar7240.a'
 Configuring for TP-Link TL-WDR3600/43x0 at: Wed Mar 23 22:25:01 PDT 2016 
/home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-gcc: line 82: /home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-musl-gcc.bin: cannot execute binary file: Exec format error
/home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-gcc: line 82: /home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-musl-gcc.bin: Success
Makefile:154: warning: overriding recipe for target '.PHONY'
Makefile:152: warning: ignoring old recipe for target '.PHONY'
Makefile:240: warning: overriding recipe for target 'board/ar7240/db12x/libdb12x.a'
Makefile:208: warning: ignoring old recipe for target 'board/ar7240/db12x/libdb12x.a'
Makefile:240: warning: overriding recipe for target 'cpu/mips/libmips.a'
Makefile:208: warning: ignoring old recipe for target 'cpu/mips/libmips.a'
Makefile:240: warning: overriding recipe for target 'cpu/mips/ar7240/libar7240.a'
Makefile:208: warning: ignoring old recipe for target 'cpu/mips/ar7240/libar7240.a'
/home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-gcc: line 82: /home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-musl-gcc.bin: cannot execute binary file: Exec format error
/home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-gcc: line 82: /home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-musl-gcc.bin: Success
/home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-gcc: line 82: /home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-musl-gcc.bin: cannot execute binary file: Exec format error
/home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-gcc: line 82: /home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-musl-gcc.bin: Success
/home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-gcc: line 82: /home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-musl-gcc.bin: cannot execute binary file: Exec format error
/home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-gcc: line 82: /home/spazz/Downloads/u-boot_mod/toolchain/bin/mips-openwrt-linux-musl-gcc.bin: Success
/home/spazz/Downloads/u-boot_mod/u-boot/config.mk:242: recipe for target 'cpu/mips/start.o' failed
make[1]: *** [cpu/mips/start.o] Error 126
Makefile:116: recipe for target 'tplink_wdr3600_43x0' failed
make: *** [tplink_wdr3600_43x0] Error 2
```

The toolchain used is what you linked to in readme. Is there another version which needs to be used or does the make file need to be adapted.

**Comment by pepe2k** [comment]
Hello stopspazzing,

The toolchain binaries are compiled for x86-64. If you are using 32-bit system, you should compile the toolchain yourself. I will update README.

Piotr
