### ISSUE TITLE
RAM version won't compile

### ISSUE THREAD

**Issue by ovctvct** [pepe2k/u-boot_mod#97]
I'm trying to compile RAM version for tl-wr841n v9, but I get this(but non-RAM images are compiled):
` 
make[1]: Entering directory `/home/ovctvct/u-boot_mod/u-boot'
> Configuring for TP-Link TL-WR841N/D v9 at: Sat Apr 2 15:26:14 EEST 2016 
make[1]: Leaving directory `/home/ovctvct/u-boot_mod/u-boot'
make[1]: Entering directory `/home/ovctvct/u-boot_mod/u-boot'
make[2]: Entering directory `/home/ovctvct/u-boot_mod/u-boot/tools'
ln -s ../common/environment.c environment.c
ln -s ../lib_generic/crc32.c crc32.c
make[2]: Leaving directory `/home/ovctvct/u-boot_mod/u-boot/tools'
make[2]: Entering directory `/home/ovctvct/u-boot_mod/u-boot/tools'
make[2]: `.depend' is up to date.
make[2]: Leaving directory `/home/ovctvct/u-boot_mod/u-boot/tools'
make -C tools all
make[2]: Entering directory `/home/ovctvct/u-boot_mod/u-boot/tools'
gcc -g -Wall -pedantic -idirafter ../include -DTEXT_BASE=0x80100000 -DUSE_HOSTCC -O2 -c mkimage.c
gcc -g -Wall -pedantic -idirafter ../include -DTEXT_BASE=0x80100000 -DUSE_HOSTCC -O2 -c crc32.c
gcc -Wall -pedantic -idirafter ../include -DTEXT_BASE=0x80100000 -DUSE_HOSTCC -O2  -o mkimage mkimage.o crc32.o
strip mkimage
gcc -g -Wall -pedantic -idirafter ../include -DTEXT_BASE=0x80100000 -DUSE_HOSTCC -O2 -c envcrc.c
gcc -g  -idirafter ../include -DTEXT_BASE=0x80100000 -DUSE_HOSTCC -c environment.c
gcc -Wall -pedantic -idirafter ../include -DTEXT_BASE=0x80100000 -DUSE_HOSTCC -O2 -o envcrc envcrc.o crc32.o environment.o
make[2]: Leaving directory `/home/ovctvct/u-boot_mod/u-boot/tools'
mips-openwrt-linux-uclibc-gcc -Wa,-gstabs -D__ASSEMBLY__  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -c -o cpu/mips/start.o /home/ovctvct/u-boot_mod/u-boot/cpu/mips/start.S
make -C `dirname lib_generic/libgeneric.a`
make[2]: Entering directory `/home/ovctvct/u-boot_mod/u-boot/lib_generic'
make[2]: Leaving directory `/home/ovctvct/u-boot_mod/u-boot/lib_generic'
make[2]: Entering directory `/home/ovctvct/u-boot_mod/u-boot/lib_generic'
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -DCONFIG_LZMA=1 -c -o crc32.o crc32.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -DCONFIG_LZMA=1 -c -o ctype.o ctype.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -DCONFIG_LZMA=1 -c -o display_options.o display_options.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -DCONFIG_LZMA=1 -c -o ldiv.o ldiv.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -DCONFIG_LZMA=1 -c -o string.o string.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -DCONFIG_LZMA=1 -c -o vsprintf.o vsprintf.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -DCONFIG_LZMA=1 -c -o LzmaWrapper.o LzmaWrapper.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -DCONFIG_LZMA=1 -c -o LzmaDecode.o LzmaDecode.c
mips-openwrt-linux-uclibc-ar crv libgeneric.a crc32.o ctype.o display_options.o ldiv.o string.o vsprintf.o LzmaWrapper.o LzmaDecode.o
a - crc32.o
a - ctype.o
a - display_options.o
a - ldiv.o
a - string.o
a - vsprintf.o
a - LzmaWrapper.o
a - LzmaDecode.o
make[2]: Leaving directory `/home/ovctvct/u-boot_mod/u-boot/lib_generic'
make -C `dirname common/libcommon.a`
make[2]: Entering directory `/home/ovctvct/u-boot_mod/u-boot/common'
make[2]: Leaving directory `/home/ovctvct/u-boot_mod/u-boot/common'
make[2]: Entering directory `/home/ovctvct/u-boot_mod/u-boot/common'
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o main.o main.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o cmd_bootm.o cmd_bootm.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o cmd_boot.o cmd_boot.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o cmd_flash.o cmd_flash.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o cmd_mem.o cmd_mem.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o cmd_custom.o cmd_custom.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o cmd_net.o cmd_net.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o cmd_nvedit.o cmd_nvedit.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o cmd_itest.o cmd_itest.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o cmd_load.o cmd_load.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o cmd_qcaclk.o cmd_qcaclk.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o command.o command.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o console.o console.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o devices.o devices.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o dlmalloc.o dlmalloc.c
mips-openwrt-linux-uclibc-gcc -Wa,-gstabs -D__ASSEMBLY__  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wa,--no-warn \
		-DENV_CRC=0 \
		-c -o environment.o environment.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o env_common.o env_common.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o env_nowhere.o env_nowhere.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o exports.o exports.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o flash.o flash.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o lists.o lists.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o env_flash.o env_flash.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o hush.o hush.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o xyzModem.o xyzModem.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o crc16.o crc16.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o s_record.o s_record.c
mips-openwrt-linux-uclibc-ar crv libcommon.a  main.o cmd_bootm.o cmd_boot.o cmd_flash.o cmd_mem.o cmd_custom.o cmd_net.o cmd_nvedit.o cmd_itest.o cmd_load.o cmd_qcaclk.o command.o console.o devices.o dlmalloc.o environment.o env_common.o env_nowhere.o exports.o flash.o lists.o env_flash.o hush.o xyzModem.o crc16.o s_record.o
a - main.o
a - cmd_bootm.o
a - cmd_boot.o
a - cmd_flash.o
a - cmd_mem.o
a - cmd_custom.o
a - cmd_net.o
a - cmd_nvedit.o
a - cmd_itest.o
a - cmd_load.o
a - cmd_qcaclk.o
a - command.o
a - console.o
a - devices.o
a - dlmalloc.o
a - environment.o
a - env_common.o
a - env_nowhere.o
a - exports.o
a - flash.o
a - lists.o
a - env_flash.o
a - hush.o
a - xyzModem.o
a - crc16.o
a - s_record.o
make[2]: Leaving directory `/home/ovctvct/u-boot_mod/u-boot/common'
make -C `dirname board/ar7240/ap143/libap143.a`
make[2]: Entering directory `/home/ovctvct/u-boot_mod/u-boot/board/ar7240/ap143'
make[2]: Leaving directory `/home/ovctvct/u-boot_mod/u-boot/board/ar7240/ap143'
make[2]: Entering directory `/home/ovctvct/u-boot_mod/u-boot/board/ar7240/ap143'
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o ap143.o ap143.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o ../common/spi_flash.o ../common/spi_flash.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o ../common/common.o ../common/common.c
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o ../common/qca-eth-953x.o ../common/qca-eth-953x.c
../common/qca-eth-953x.c: In function 'ath_gmac_enet_initialize':
../common/qca-eth-953x.c:584:4: warning: implicit declaration of function 'athrs27_reg_init_lan' [-Wimplicit-function-declaration]
../common/qca-eth-953x.c:603:19: warning: unused variable 'mac' [-Wunused-variable]
mips-openwrt-linux-uclibc-gcc  -O  -D__KERNEL__ -DTEXT_BASE=0x80100000 -I/home/ovctvct/u-boot_mod/u-boot/include -fno-builtin -ffreestanding -nostdinc -isystem /home/ovctvct/u-boot_mod/toolchain/bin/../lib/gcc/mips-openwrt-linux-uclibc/4.6.3/include -pipe  -DCONFIG_MIPS -D__MIPS__ -G 0 -mabicalls -fpic -msoft-float -mips32 -march=mips32 -mtune=mips32 -EB -fno-schedule-insns -fno-schedule-insns2 -Wall -Wstrict-prototypes  -c -o ../common/ath_pci.o ../common/ath_pci.c
../common/ath_pci.c: In function 'plat_dev_init':
../common/ath_pci.c:137:3: warning: passing argument 2 of 'ath_pci_write_config' makes integer from pointer without a cast [enabled by default]
../common/ath_pci.c:64:1: note: expected 'pci_dev_t' but argument is of type 'void *'
../common/ath_pci.c:139:3: warning: passing argument 2 of 'ath_pci_write_config' makes integer from pointer without a cast [enabled by default]
../common/ath_pci.c:64:1: note: expected 'pci_dev_t' but argument is of type 'void *'
../common/ath_pci.c:141:2: warning: passing argument 2 of 'ath_pci_write_config' makes integer from pointer without a cast [enabled by default]
../common/ath_pci.c:64:1: note: expected 'pci_dev_t' but argument is of type 'void *'
../common/ath_pci.c: At top level:
../common/ath_pci.c:221:1: error: conflicting types for 'pci_init_board'
/home/ovctvct/u-boot_mod/u-boot/include/common.h:234:6: note: previous declaration of 'pci_init_board' was here
../common/ath_pci.c: In function 'pci_init_board':
../common/ath_pci.c:229:2: warning: 'return' with a value, in function returning void [enabled by default]
../common/ath_pci.c:385:2: warning: implicit declaration of function 'pci_set_region' [-Wimplicit-function-declaration]
../common/ath_pci.c:400:2: warning: implicit declaration of function 'pci_register_hose' [-Wimplicit-function-declaration]
../common/ath_pci.c:402:2: warning: implicit declaration of function 'pci_set_ops' [-Wimplicit-function-declaration]
../common/ath_pci.c:403:4: error: 'pci_hose_read_config_byte_via_dword' undeclared (first use in this function)
../common/ath_pci.c:403:4: note: each undeclared identifier is reported only once for each function it appears in
../common/ath_pci.c:404:4: error: 'pci_hose_read_config_word_via_dword' undeclared (first use in this function)
../common/ath_pci.c:406:4: error: 'pci_hose_write_config_byte_via_dword' undeclared (first use in this function)
../common/ath_pci.c:407:4: error: 'pci_hose_write_config_word_via_dword' undeclared (first use in this function)
../common/ath_pci.c: At top level:
../common/ath_pci.c:42:1: warning: 'ath_local_read_config' defined but not used [-Wunused-function]
make[2]: *** [../common/ath_pci.o] Error 1
make[2]: Leaving directory `/home/ovctvct/u-boot_mod/u-boot/board/ar7240/ap143'
make[1]: *** [board/ar7240/ap143/libap143.a] Error 2
make[1]: Leaving directory `/home/ovctvct/u-boot_mod/u-boot'
make: *** [tplink_wr841n_v9] Error 2
`

**Comment by pepe2k** [comment]
Fixed!
